### ISSUE TITLE
Adding a task does not work if it contains an apostrophe

### ISSUE THREAD

**Issue by TheThunderChimp** [ybibaev/alfred-todoist-simple#4]
Adding a task does not seem to work if the task contains an apostrophe. For example, using the workflow to add "Do not bite nails" works, but using it to add "Don't bite nails" does not:

![CleanShot 2022-12-26 at 12 20 43 Github  CS](https://user-images.githubusercontent.com/121452216/209571411-ab684e40-159c-471a-be35-ef28beeb897e.png)
![CleanShot 2022-12-26 at 12 22 41 Github  CS](https://user-images.githubusercontent.com/121452216/209571415-5dcc2d4b-0951-4181-b02d-523c029e97e9.png)

**Comment by ybibaev** [comment]
Good catch!
I'm going to prepare a fix in a few days.

**Comment by ybibaev** [comment]
It's been fixed. Please check the latest version. 
Thank you for your report.
